version: "3.8"
services: 
    watchtogether_db:
      build:
        context: .
        dockerfile: redis.Dockerfile
      ports:
        - "6379:6379"
    watchtogether_db_admin:
      image: rediscommander/redis-commander:latest
      environment:
      - REDIS_HOSTS=local:db:6379
      ports:
      - "8081:8081"
      links:
        - "watchtogether_db:db"
      depends_on: 
        - watchtogether_db
    watchtogether_server:
      build: .
      ports:
        - "8080:8080"
      links: 
        - "watchtogether_db:db"
      depends_on: 
        - watchtogether_db
      environment: 
        - NODE_ENV=production
        - DEBUG=watchtogether*
      env_file: .env